spring:
  datasource:
    url: jdbc:h2:mem:familyhub;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jackson:
    time-zone: UTC
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: "familyhub-demo-secret-familyhub-demo-secret-2026"
    access-token-ttl: 7d
    refresh-token-ttl: 30d
