spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.0.106}:${DB_PORT:3306}/${DB_NAME:familyhub}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:satan}
    password: ${DB_PASSWORD:wjz19940823}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  jackson:
    time-zone: UTC
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: "familyhub-demo-secret-familyhub-demo-secret-2026"
    access-token-ttl: 7d
    refresh-token-ttl: 30d
